[versions]
jupiter = "5.9.2"
kotlin = "1.7.20"
benchmark = "0.4.7"

[libraries]
kotest = "io.kotest:kotest-assertions-core:5.5.4"
ktlint = { module = "com.pinterest.ktlint:ktlint-core", version = "0.47.1" }

jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter" }
jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter" }

benchmark = { module = "org.jetbrains.kotlinx:kotlinx-benchmark-runtime", version.ref = "benchmark" }
serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
jmh = { id = "me.champeau.jmh", version = "0.6.8" }
benchmark = { id = "org.jetbrains.kotlinx.benchmark", version.ref = "benchmark" }
compose = { id = "org.jetbrains.compose", version = "1.2.2" }
kotlinter = { id = "org.jmailen.kotlinter", version = "3.13.0" }
