[versions]
jupiter = "5.10.1"
kotlin = "1.9.21"
ktlintGradlePlugin = "12.0.2"

[libraries]
kotest = "io.kotest:kotest-assertions-core:5.8.0"
ktlint = "com.pinterest.ktlint:ktlint-cli:1.0.1"
ktlintGradlePlugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlintGradlePlugin" }
coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"
okhttp = "com.squareup.okhttp3:okhttp:4.12.0"

jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter" }
jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter" }

serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.2"
kotlin-jvmPlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradlePlugin" }
