[versions]
jupiter = "5.11.3"
kotlin = "2.0.21"
ktlintGradlePlugin = "12.1.1"

[libraries]
kotest = "io.kotest:kotest-assertions-core:5.9.1"
ktlint = "com.pinterest.ktlint:ktlint-cli:1.4.0"
ktlintGradlePlugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlintGradlePlugin" }
coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0"
okhttp = "com.squareup.okhttp3:okhttp:4.12.0"
clikt = "com.github.ajalt.clikt:clikt:4.4.0"
kotlinPoet = "com.squareup:kotlinpoet:2.0.0"

jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter" }
jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter" }

serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3"
kotlin-jvmPlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradlePlugin" }
